name = "Breeze"
uuid = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
version = "0.1.2"
authors = ["Navid C. Constantinou <navidcy@users.noreply.github.com>, Gregory L. Wagner, Madi, Marty, Callum, and Paul"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RRTMGP = "a01a1ee8-cea4-48fc-987c-fc7878d79da1"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"

[compat]
Adapt = "4.3.0"
AtmosphericProfilesLibrary = "0.1.7"
ClimaComms = "0.6.9"
ClimaParams = "0.10.35"
CloudMicrophysics = "0.22.13"
JLD2 = "0.5.13"
Oceananigans = "0.99"
Printf = "1"
RRTMGP = "0.21.4"
RootSolvers = "0.4.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
