[deps]
AtmosphericProfilesLibrary = "86bc3604-9858-485a-bdbe-831ec50de11d"
Breeze = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CloudMicrophysics = "6a9e3e04-43cd-43ba-94b9-e8782df3c71b"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RRTMGP = "a01a1ee8-cea4-48fc-987c-fc7878d79da1"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[sources]
Breeze = {path = ".."}

[compat]
AtmosphericProfilesLibrary = "0.1.7"
CloudMicrophysics = "0.22.13, 0.29"
NCDatasets = "0.14"
Oceananigans = "0.104"
