name = "BreezeBenchmarks"
uuid = "bf6d035f-d60d-49bd-b9cb-a5154202673a"
version = "0.1.0"
authors = ["NumericalEarth organization (github.com/NumericalEarth) and contributors"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Breeze = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
Breeze = {path = ".."}

[compat]
ArgParse = "1"
BenchmarkTools = "1"
Breeze = "0.3"
CUDA = "5"
Dates = "<0.0.1, 1"
DocStringExtensions = "0.9"
JLD2 = "0.5, 0.6"
JSON = "1.4.0"
KernelAbstractions = "0.9"
Oceananigans = "0.104"
Printf = "1"
Statistics = "<0.0.1, 1"
julia = "1.10"
