[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[compat]
Documenter = "1"

[sources]
Documenter = {url = "https://github.com/giordano/documenter.jl", rev = "mg/post-github-status-deploydoc"}
