name: CI

on:
  push:
    branches:
      - "main"
    paths: &paths
      - ".github/workflows/CI.yml"
      - "ext/**"
      - "src/**"
      - "test/**"
      - "Project.toml"
  pull_request:
    paths: *paths
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    container:
      image: ${{ (startsWith(matrix.os, 'aws-linux-nvidia-gpu-') && 'ghcr.io/numericalearth/breeze-docker-images:test' ) || '' }}
      options: --gpus=all
    strategy:
      fail-fast: false
      matrix:
        version:
          - "min"
          - "1.12.2"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - "default"
        exclude:
          - version: "min"
            os: windows-latest
        include:
          - version: "1.12.2"
            os: aws-linux-nvidia-gpu-t4
            arch: "default"
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        # On the self-hosted GPU runners we use a Docker image with Julia pre-installed.
        if: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
        id: julia-cache
        # On self-hosted runners we don't use the cache: in re-use mode we run on a machine
        # which has just run another job, which would conflict with the existing cache.
        if: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
      - name: "Set test arguments and other environment variables"
        shell: bash
        run: |
          # Run tests in verbose mode
          TEST_ARGS=(--verbose)

          if [[ ${{ matrix.os }} == *linux-nvidia-gpu* ]]; then
              # When running the tests on a GPU node we always want to make sure
              # CUDA is functional.
              echo "BREEZE_ENSURE_CUDA_FUNCTIONAL=true" >> "${GITHUB_ENV}"
          fi

          if [[ ${{ runner.os }} == "macOS" ]]; then
              # Encourage ParallelTestRunner to use two jobs on macOS, rather
              # than the single one it'd use by default.
              TEST_ARGS+=(--jobs=2)
          fi
          echo "runtest_test_args=${TEST_ARGS[@]}" >> "${GITHUB_ENV}"
      - name: Prepare test environment
        if: ${{ startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        shell: bash
        run: |
          # Running doctests need to run `git` commands in this directory, but `git`
          # complains about dubious ownership when using the Docker image.
          git config --global --add safe.directory ${PWD}

          # Little complication: we built the Docker images on a non-GPU system and so we
          # had to use a `LocalPreferences.toml` file to force the CUDA runtime, but this
          # means that we have to use the same preferences also for the tests environment,
          # because running the tests clears up the load path.  Let's copy the global
          # preference file to test directory (the global one will be ignored during the
          # tests), and add `CUDA_Runtime_jll` to the env to make the preference effective.
          cp /usr/local/share/julia/environments/breeze/LocalPreferences.toml test/.
          julia --project=test --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add("CUDA_Runtime_jll")'
      - name: Run tests
        shell: bash
        run: |
          if [[ ${{ matrix.os }} == aws-linux-nvidia-gpu* ]]; then
              # We use earlyoom only on the GPU machines
              earlyoom -m 3 -s 100 -r 300 --prefer 'julia' &
          fi
          julia --project --color=yes -e 'using Pkg; Pkg.test(; coverage=true, julia_args=["--check-bounds=yes", "--compiled-modules=yes", "--depwarn=yes"], test_args=`${{ env.runtest_test_args }}`, force_latest_compatible_version=false, allow_reresolve=true)'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
        continue-on-error: true
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') && (cancelled() || failure()) }}
        uses: actions/cache/save@v5
        with:
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
