name: CI

on:
  push:
    branches:
      - "main"
    paths: &paths
      - ".github/workflows/CI.yml"
      - "ext/**"
      - "src/**"
      - "test/**"
      - "Project.toml"
  pull_request:
    paths: *paths
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

env:
  # Disable GPU support for Reactant until we actually use it.
  REACTANT_GPU: 'none'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 75
    container:
      image: ${{ (startsWith(matrix.os, 'aws-linux-nvidia-gpu-') && format('ghcr.io/numericalearth/breeze-docker-images:test-julia_{0}', matrix.version) ) || '' }}
      options: --gpus=all
    strategy:
      fail-fast: false
      matrix:
        version:
          - "min"
          - "1.12.5"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - "default"
        exclude:
          - version: "min"
            os: windows-latest
        include:
          - version: "1.12.4"
            os: aws-linux-nvidia-gpu-l4
            arch: "default"
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        # On the self-hosted GPU runners we use a Docker image with Julia pre-installed.
        if: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
        id: julia-cache
        with:
          # On self-hosted runners we use the prebuilt Docker container, which already
          # caches pkgimages and such, so we don't need to cache here most things.  Only
          # useful thing is the scratchspaces, in particular ParallelTestRunner's to make
          # scheduling of test jobs more efficients.
          cache-artifacts: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-packages: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-registries: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-compiled: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
          cache-scratchspaces: true
          cache-logs: ${{ ! startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
      - name: "Set test arguments and other environment variables"
        shell: bash
        run: |
          # Run tests in verbose mode
          TEST_ARGS=(--verbose)

          if [[ ${{ matrix.os }} == *linux-nvidia-gpu* ]]; then
              # When running the tests on a GPU node we always want to make sure
              # CUDA is functional.
              echo "BREEZE_ENSURE_CUDA_FUNCTIONAL=true" >> "${GITHUB_ENV}"
              # On the GPU runners we sometimes run out-of-memory because we have several
              # concurrent jobs, some of them reaching a large memory usage.  We reduce the
              # number of jobs to avoid memory issues.
              TEST_ARGS+=(--jobs=$(($(nproc) - 1)))
          fi

          if [[ ${{ runner.os }} == "macOS" ]]; then
              # Encourage ParallelTestRunner to use two jobs on macOS, rather
              # than the single one it'd use by default.
              TEST_ARGS+=(--jobs=2)
          fi
          echo "runtest_test_args=${TEST_ARGS[@]}" | tee "${GITHUB_ENV}"
      - name: Prepare test environment
        if: ${{ startsWith(matrix.os, 'aws-linux-nvidia-gpu-') }}
        shell: bash
        run: |
          # Running doctests need to run `git` commands in this directory, but `git`
          # complains about dubious ownership when using the Docker image.
          git config --global --add safe.directory ${PWD}

          # Little complication: we built the Docker images on a non-GPU system and so we
          # had to use a `LocalPreferences.toml` file to force the CUDA runtime, but this
          # means that we have to use the same preferences also for the tests environment,
          # because running the tests clears up the load path.  Let's copy the global
          # preference file to test directory (the global one will be ignored during the
          # tests), and add `CUDA_Runtime_jll` to the env to make the preference effective.
          cp /usr/local/share/julia/environments/breeze/LocalPreferences.toml test/.
          julia --project=test --color=yes --check-bounds=yes -e 'using Pkg; Pkg.Registry.update(); Pkg.add("CUDA_Runtime_jll")'
      - name: Run tests
        shell: bash
        run: |
          if [[ ${{ matrix.os }} == aws-linux-nvidia-gpu* ]]; then
              # We use earlyoom only on the GPU machines
              earlyoom -m 3 -s 100 -r 300 --prefer 'julia' &
          fi
          julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test(; coverage=true, julia_args=["--check-bounds=yes", "--compiled-modules=yes", "--depwarn=yes", "-O0"], test_args=`${{ env.runtest_test_args }}`, force_latest_compatible_version=false, allow_reresolve=true)'
        env:
          # Don't make Reactant occupy all the GPU memory
          XLA_REACTANT_GPU_PREALLOCATE: false
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
        continue-on-error: true
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        # Avoid wasting time saving the cache on Windows, it takes long to both
        # save it and fetch it back.
        if: ${{ (runner.os != 'Windows') && (cancelled() || failure()) }}
        uses: actions/cache/save@v5
        with:
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
