name: Documentation

on:
  push:
    branches:
      - main
    tags: "*"
    paths:
      - ".github/workflows/Documentation.yml"
      - "docs/**"
      - "src/**"
      - "Project.toml"
      - "CHANGELOG.md"
  pull_request:
    paths:
      - ".github/workflows/Documentation.yml"
      - "docs/**"
      - "src/**"
      - "Project.toml"
      - "CHANGELOG.md"
  release:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.12"
      - uses: julia-actions/cache@v2
        id: julia-cache
      - name: Instantiate docs environment
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Build documentation
        run:
          julia --color=yes --project=docs docs/make.jl
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
      - uses: actions/upload-artifact@v4
        with:
          name: documentation-build
          path: docs/build
          retention-days: 10

  deploy-docs:
    needs: build-docs
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      # Have only one job pushing the docs at a time.
      group: docs-pushing
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.12"
      - uses: julia-actions/cache@v2
        id: julia-cache
      - uses: actions/download-artifact@v5
        with:
          name: documentation-build
      - name: Instantiate docs environment
        shell: julia --color=yes {0}
        run: |
          # We only need `Documenter` for publishing the docs, let's not
          # reinstall the world all over again.
          using Pkg
          Pkg.add(; name="Documenter", version="1")
      - name: Build documentation
        run:
          julia --color=yes docs/deploy.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.BREEZEDOCUMENTATION_DOCUMENTER_KEY }}
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
