name: Documentation

on:
  push:
    branches:
      - '**'
    tags: "*"
    paths: &paths
      - ".github/workflows/Documentation.yml"
      - "docs/**"
      - "examples/**"
      - "src/**"
      - "Project.toml"
      - "CHANGELOG.md"
  # pull_request:
  #   paths: *paths

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BREEZE_LABEL_BUILD_ALL_EXAMPLES: 'build all examples üèóÔ∏è'

jobs:
  build-docs:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        os:
          # - aws-linux-nvidia-gpu-t4
          - aws-linux-nvidia-gpu-l4
    runs-on: ${{ matrix.os }}
    container:
      image: 'ghcr.io/numericalearth/breeze-docker-images:docs-julia_1.12.4'
      options: --gpus=all
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - name: Set BREEZE_BUILD_ALL_EXAMPLES
        shell: bash
        run: |
          if [[ ('${{ github.event_name }}' == 'push' && ('${{ github.ref }}' == 'refs/heads/main') || '${{ github.ref }}' == refs/tags/v*) || ('${{ github.event_name }}' == 'release') || ('${{ github.event_name }}' == 'pull_request' && ${{ contains(github.event.pull_request.labels.*.name,  env.BREEZE_LABEL_BUILD_ALL_EXAMPLES) }} == true) ]]; then
              BREEZE_BUILD_ALL_EXAMPLES=true
          else
              BREEZE_BUILD_ALL_EXAMPLES=false
          fi
          echo "BREEZE_BUILD_ALL_EXAMPLES=${BREEZE_BUILD_ALL_EXAMPLES}" | tee "${GITHUB_ENV}"
      - name: Instantiate docs environment
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Prepare environment
        shell: bash
        run: |
          # Running doctests need to run `git` commands in this directory, but `git`
          # complains about dubious ownership when using the Docker image.
          git config --global --add safe.directory ${PWD}
      - name: Run example
        shell: bash
        timeout-minutes: 45
        run:
          earlyoom -m 3 -s 100 -r 300 --prefer 'julia' &
          julia --color=yes --project=docs examples/splitting_supercell.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: cuda-dump
          path: microphysical_update
          retention-days: 90
      # - uses: actions/upload-artifact@v6
      #   with:
      #     name: documentation-build
      #     path: docs/build
      #     retention-days: 10

  deploy-docs:
    # We want to deploy docs if:
    # * it's a push, but only to main
    # * it's a PR, but not from a fork
    # * on a release
    if: ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))) || (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'release') }}
    needs: build-docs
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      # Have only one job pushing the docs at a time.
      group: docs-pushing
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.12.4"
      - uses: julia-actions/cache@v2
        id: julia-cache
      - uses: actions/download-artifact@v7
        with:
          name: documentation-build
          path: docs/build
      - name: Remove extra files
        # There may be JLD2 files generated during execution of Literate
        # examples, we don't need them on the website.
        run:
          rm -fv docs/build/literated/*.jld2
      - name: Instantiate docs environment
        shell: julia --color=yes {0}
        run: |
          # We only need `Documenter` for publishing the docs, let's not
          # reinstall the world all over again.
          using Pkg
          Pkg.add(; name="Documenter", version="1")
      - name: Deploy documentation
        run:
          julia --color=yes docs/deploy.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.BREEZEDOCUMENTATION_DOCUMENTER_KEY }}
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v5
        with:
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
